# application.yml 설정
spring:
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true

# server 관련 설정
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Swagger springdoc-ui 설정
springdoc:
  packages-to-scan: com.book.dalant.web.rest
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
    cache:
      disabled: true

application: